# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20170725_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
