# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20170717_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='Name',
        ),
    ]
